# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i0AQpvtsgdPS56WLx1r-_mkrYp7DU0Od

# Урок - 26.05.2023
"""

print('Hello world');

x = 5;
y = 'Hello world';
x = 10;
z = 1.05;
arr = [1, 2, 3, 'I am here', 0.4];

print(type(x));
print(type(y));
print(type(z));
print(type(arr));
print(arr[3]);
print(len(arr));

x = 20
у = 0

try:
  a = x / у;
  print(a);
except ZeroDivisionError:
  print('Упсс, кажется вы пытаетесь поделить на 0 :(');

try:
  x = int(input('Что вы хотите поделить? '))
  y = int(input('На что вы хотите поделить? '))
  a = x / y
  print(a)
except ZeroDivisionError:
  print('Упсс, кажется вы пытаетесь поделить на 0 :(');
finally:
  print('You are pretty =)'); # выводится и для try и для except

import random
a = random.randint(30, 100);
print(a)

import random
arr = [1, 2, 3, 'I am here', 0.4];

a = random.choice(arr);
print(a)

l = random.random();
print(l); # от 0 до 1

# задача с игральным кубиком ( свой вариант )
import random
cube = [1, 2, 3, 4, 5, 6];

oneCube = random.choice(cube);
print(oneCube)
twoCube = random.choice(cube);
print(twoCube)
threeCube = random.choice(cube);
print(threeCube)
fourCube = random.choice(cube);
print(fourCube)

common = oneCube + twoCube + threeCube + fourCube;
print(common);

# задача с игральным кубиком ( решение учителя )

brocok1 = random.randint(1, 6);
brocok2 = random.randint(1, 6);
brocok3 = random.randint(1, 6);
brocok4 = random.randint(1, 6);

total = brocok1 + brocok2 + brocok3 + brocok4

print('Бросок №1: ',brocok1, 'Бросок №2: ',brocok2, 'Бросок №3: ',brocok3, 'Бросок №4: ',brocok4,);
print('Всего очков: ',total)

# задача с игральным кубиком ( решение учителя v2 )
import random

x = 4
y = []
total = 0

while x != 0:
  brocok = random.randint(1, 6);
  x -= 1;
  y.append(brocok);
  
print(y);
# total = sum(y); 

for i in y:
  total += i;

print("Всего очков: ", total);

# генератор паролей
import random;
chars = '+-/*!&$#?=@<>abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';
length = input('Какой длины нужен пароль? ');
password = '';

try:
  length = int(length);
  for i in range(length):
    password += random.choice(chars);

  print(password);
except ValueError:
  print('Упсс, вы ввели буквы. Прошу написать цифры =)');
  length = input('Попробуйте еще раз, какой длины нужен пароль? ');
  length = int(length);
  for i in range(length):
    password += random.choice(chars);

  print(password);