# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i0AQpvtsgdPS56WLx1r-_mkrYp7DU0Od
"""

print('Hello world');